name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  image-name:
    description: 'Short name of the image (without the registry name)'
    required: true
  image-tag:
    description: 'Version tag of the image'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: false
    default: "Dockerfile"
  context-path:
    description: 'Path where to run docker build'
    required: false
    default: "."
  push:
    description: 'Wether to push image or not'
    required: false
    default: "False"
  ecr-region:
    description: 'AWS ECR region to login to'
    required: false
    default: ""

outputs:
  registry:
    description: 'The registry where the image has been pushed'
  image-fullname: # output will be available to future steps
    description: 'The full name of the image with registry, name and tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
